name: Test readline
on: [push]
jobs:
  test:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ./
        with:
          ruby-version: 2.4.1

      - run: ruby -v
      - run: ruby -rreadline -e 'p Readline'
